#  Deploy the vendor portal to cpanel based on environment
name: Deploy Vendor React app to cpanel

on:
    push:
        branches:
            - main
            - test

jobs:
    deploy: 
        runs-on: ubuntu-latest
        if: |
            !contains(github.event.head_commit.message, '[skip deploy]')

        # Set the environment
        environment: ${{ github.ref_name == 'main' && 'prod' || 'test' }}

        env:
            REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm ci

            - name: Build React app
              env: 
                REACT_APP_API_BASE_URL: ${{ vars.REACT_APP_API_BASE_URL }}
                REACT_APP_FAV_ICON: ${{ vars.REACT_APP_FAV_ICON }}
              run: |
                    echo "Bulding react app with API URL: $REACT_APP_API_BASE_URL"
                    CI=false npm run build
            
            # upload in versions folder like versions/version-1, version-2
            - name: Upload release
              uses: appleboy/scp-action@v0.1.6
              with:
                host: ${{ secrets.CPANEL_HOST }}
                username: ${{ secrets.CPANEL_USERNAME }}
                key: ${{ secrets.CPANEL_SSH_KEY }}
                source: "build/*"
                target: "/home/${{ secrets.CPANEL_USERNAME }}/${{ secrets.DEPLOY_DIR }}/versions/version-${{ github.run_number }}"
               
            - name: Activate Release 
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.CPANEL_HOST }}
                  username: ${{ secrets.CPANEL_USERNAME }}
                  key: ${{ secrets.CPANEL_SSH_KEY }}
                  script: |
                        set -e
                        cd "/home/${{ secrets.CPANEL_USERNAME }}/${{ secrets.DEPLOY_DIR }}"
                        if [ ! -d "versions/version-${{ github.run_number }}" ]; then
                            echo "Versions directory does not exist. Creating it now."
                            mkdir -p "versions"
                        fi

                        ln -sfn "versions/version-${{ github.run_number }}/build" current/build
                        echo "Activated version-${{ github.run_number }} as the current release."

            